/**
 * lib/pdf/certificate.tsx
 * @react-pdf/renderer document component for AllergenWise certificates.
 *
 * Spec from MVP_BUILD §11:
 * - Letter landscape, white background
 * - Teal-700 (#0f766e) double border: 4px outer + 1px inner, 12px from page edge
 * - AllergenWise mark: teal-700 rounded-square with "AW" in white 24pt bold
 * - Eyebrow: "CERTIFICATE OF COMPLETION" 10pt ink.500 letterSpacing 0.2em uppercase
 * - Heading: "AllergenWise Certified Staff" 28pt Georgia bold centered
 * - Recipient: 40pt Georgia italic centered
 * - Body: 12pt justified, max 500pt wide
 * - 3-col footer: Issued / Expires / Cert ID (label 9pt ink.500 + value 11pt ink.900)
 * - QR code PNG data URL bottom-right, 60×60pt
 * - Verify URL caption 8pt ink.500 below QR
 *
 * Props: CertificateDocumentProps (includes qrDataUrl generated by render.ts)
 */

import React from 'react';
import path from 'path';
import { DISCLAIMER, CERT_NAME } from '@/lib/disclaimer';
import { Document, Page, View, Text, Image, StyleSheet, Font } from '@react-pdf/renderer';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CertificateDocumentProps {
  certCode: string;
  recipientName: string;
  restaurantName: string;
  issuedAt: string; // ISO string or YYYY-MM-DD
  expiresAt: string; // ISO string or YYYY-MM-DD
  verifyUrl: string; // Full URL for QR code target
  qrDataUrl: string; // PNG data URL from qrcode library (generated by render.ts)
}

// ─── Design tokens ────────────────────────────────────────────────────────────

const TEAL_700 = '#0f766e';
const INK_900 = '#1a2332';
const INK_500 = '#6b7589';
const WHITE = '#ffffff';
const BORDER = '#e3e6eb';

// ─── Font registration ────────────────────────────────────────────────────────
// Register Crimson Text using locally embedded TTF files so PDF generation works
// in offline and restricted-network environments (CI, Vercel cold starts, etc.).
//
// Font files live at lib/pdf/fonts/ — committed to the repo under OFL-1.1.
// @react-pdf/renderer v4 calls fontkit.open(src) when src is a filesystem path
// (not a URL, not a data URL), so absolute paths work natively in Node.js.
//
// process.cwd() is the project root both locally and on Vercel (/var/task),
// so path.join(process.cwd(), 'lib/pdf/fonts', ...) resolves correctly in both
// environments. No network call is made at render time.
//
// Font weight 600 (SemiBold) is mapped to fontWeight: 'bold' — @react-pdf/renderer
// maps 'bold' → 700, but with only 400/600 available, 600 is the closest match.

const FONTS_DIR = path.join(process.cwd(), 'lib', 'pdf', 'fonts');

Font.register({
  family: 'Georgia',
  fonts: [
    {
      src: path.join(FONTS_DIR, 'CrimsonText-Regular.ttf'),
      fontStyle: 'normal',
      fontWeight: 'normal',
    },
    {
      src: path.join(FONTS_DIR, 'CrimsonText-Italic.ttf'),
      fontStyle: 'italic',
      fontWeight: 'normal',
    },
    {
      src: path.join(FONTS_DIR, 'CrimsonText-SemiBold.ttf'),
      fontStyle: 'normal',
      fontWeight: 'bold',
    },
  ],
});

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    backgroundColor: WHITE,
    padding: 0,
    position: 'relative',
  },

  // Outer border — 4px teal-700, 12px from page edge
  outerBorder: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    bottom: 12,
    borderWidth: 4,
    borderColor: TEAL_700,
    borderStyle: 'solid',
  },

  // Inner border — 1px teal-700, 4px gap inside outer (12+4+2=18 from edge + gap)
  innerBorder: {
    position: 'absolute',
    top: 20,
    left: 20,
    right: 20,
    bottom: 20,
    borderWidth: 1,
    borderColor: TEAL_700,
    borderStyle: 'solid',
  },

  // Content area — inside the double border
  content: {
    position: 'absolute',
    top: 24,
    left: 24,
    right: 24,
    bottom: 24,
    paddingTop: 28,
    paddingHorizontal: 40,
    paddingBottom: 20,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },

  // AllergenWise mark: teal-700 rounded square
  markContainer: {
    width: 56,
    height: 56,
    backgroundColor: TEAL_700,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },

  markText: {
    color: WHITE,
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 1,
  },

  // "CERTIFICATE OF COMPLETION" — eyebrow
  eyebrow: {
    fontSize: 9,
    color: INK_500,
    letterSpacing: 4, // ~0.2em at 9pt (react-pdf uses pt units for letterSpacing)
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 8,
  },

  // "AllergenWise Certified Staff" — 28pt Georgia bold
  headingTitle: {
    fontSize: 28,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    color: INK_900,
    textAlign: 'center',
    marginBottom: 6,
  },

  // Divider
  divider: {
    width: 80,
    height: 1,
    backgroundColor: TEAL_700,
    marginVertical: 12,
    alignSelf: 'center',
  },

  // "This is to certify that"
  herbyText: {
    fontSize: 11,
    color: INK_500,
    textAlign: 'center',
    marginBottom: 4,
  },

  // Recipient name — 40pt Georgia italic
  recipientName: {
    fontSize: 40,
    fontFamily: 'Georgia',
    fontStyle: 'italic',
    color: INK_900,
    textAlign: 'center',
    marginBottom: 10,
  },

  // Body paragraph — 12pt, justified, max 500pt wide
  bodyText: {
    fontSize: 12,
    color: INK_500,
    textAlign: 'justify',
    maxWidth: 500,
    lineHeight: 1.55,
    marginBottom: 16,
    alignSelf: 'center',
  },

  // Required Disclaimer Language (verbatim, from lib/disclaimer.ts)
  disclaimer: {
    fontSize: 8,
    color: INK_500,
    textAlign: 'center',
    maxWidth: 500,
    lineHeight: 1.4,
    marginBottom: 10,
    alignSelf: 'center',
  },

  // 3-column footer — Issued / Expires / Cert ID
  footer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 'auto',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: BORDER,
    borderTopStyle: 'solid',
  },

  footerCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },

  footerColCenter: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },

  footerColRight: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },

  // Footer label — 9pt ink.500
  footerLabel: {
    fontSize: 9,
    color: INK_500,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 2,
  },

  // Footer value — 11pt ink.900
  footerValue: {
    fontSize: 11,
    color: INK_900,
    fontWeight: 'bold',
  },

  // Cert ID — monospace for visual distinction
  footerValueMono: {
    fontSize: 10,
    color: INK_900,
    fontFamily: 'Courier',
    letterSpacing: 0.5,
  },

  // QR code — absolute bottom-right
  qrContainer: {
    position: 'absolute',
    bottom: 32,
    right: 44,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },

  qrImage: {
    width: 60,
    height: 60,
  },

  qrCaption: {
    fontSize: 8,
    color: INK_500,
    marginTop: 3,
    textAlign: 'right',
    maxWidth: 90,
  },
});

// ─── Date formatter ───────────────────────────────────────────────────────────

function formatDate(isoString: string): string {
  const d = new Date(isoString);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// ─── Certificate Document ─────────────────────────────────────────────────────

export function CertificateDocument({
  certCode,
  recipientName,
  restaurantName,
  issuedAt,
  expiresAt,
  verifyUrl,
  qrDataUrl,
}: CertificateDocumentProps) {
  // Strip protocol for the caption text
  const captionUrl = verifyUrl.replace(/^https?:\/\//, '');

  return (
    <Document
      title={`AllergenWise Certificate — ${recipientName}`}
      author="AllergenWise"
      creator="AllergenWise"
      subject="Food Allergen Safety Certification"
    >
      <Page size="LETTER" orientation="landscape" style={styles.page}>
        {/* Double-line border frame */}
        <View style={styles.outerBorder} />
        <View style={styles.innerBorder} />

        {/* Main content column */}
        <View style={styles.content}>
          {/* AllergenWise mark — teal rounded square with AW */}
          <View style={styles.markContainer}>
            <Text style={styles.markText}>AW</Text>
          </View>

          {/* Eyebrow — certification name (verbatim, imported — never inlined) */}
          <Text style={styles.eyebrow}>{CERT_NAME}</Text>

          {/* Heading */}
          <Text style={styles.headingTitle}>AllergenWise Certified Staff</Text>

          {/* Divider line */}
          <View style={styles.divider} />

          {/* Preamble */}
          <Text style={styles.herbyText}>This is to certify that</Text>

          {/* Recipient name — 40pt Georgia italic */}
          <Text style={styles.recipientName}>{recipientName}</Text>

          {/* Body paragraph — 12pt, justified */}
          <Text style={styles.bodyText}>
            has successfully completed the AllergenWise Food Allergen Safety Training program and
            passed the certification examination at {restaurantName}. This certificate demonstrates
            competency in identifying the major food allergens, preventing cross-contact, and
            responding to allergen emergencies in accordance with FDA Food Code standards.
          </Text>

          {/* Required Disclaimer Language (verbatim, imported — never inlined) */}
          <Text style={styles.disclaimer}>{DISCLAIMER}</Text>

          {/* 3-column footer */}
          <View style={styles.footer}>
            <View style={styles.footerCol}>
              <Text style={styles.footerLabel}>Issued</Text>
              <Text style={styles.footerValue}>{formatDate(issuedAt)}</Text>
            </View>

            <View style={styles.footerColCenter}>
              <Text style={styles.footerLabel}>Expires</Text>
              <Text style={styles.footerValue}>{formatDate(expiresAt)}</Text>
            </View>

            <View style={styles.footerColRight}>
              <Text style={styles.footerLabel}>Cert ID</Text>
              <Text style={styles.footerValueMono}>{certCode}</Text>
            </View>
          </View>
        </View>

        {/* QR code — absolute position, bottom-right inside inner border */}
        <View style={styles.qrContainer}>
          {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer Image is not an HTML img; no alt needed */}
          <Image src={qrDataUrl} style={styles.qrImage} />
          <Text style={styles.qrCaption}>{captionUrl}</Text>
        </View>
      </Page>
    </Document>
  );
}
