-- ─── Migration 0015 — Wave 4B random cert codes ────────────────────────────
--
-- P0 #10.a: replace sequential `AW-{year}-{6-digit-seq}` cert codes with
-- random Crockford Base32 codes + ISO 7064 Mod 37,36 check digit.
--
-- Format: AW-XXXXX-XXXXX-C where the 10 body characters draw from
-- Crockford Base32 (0-9, A-Z minus I, L, O, U) and C is the check digit.
-- The check digit is generated with rejection sampling so it also draws
-- from the Crockford alphabet (never I/L/O/U) — this preserves the
-- 100%-single-substitution-detection guarantee of ISO 7064 Mod 37,36.
--
-- Pre-launch: NO production-issued codes exist. Dev/test databases are
-- regenerated by `pnpm db:reset`. The CHECK constraint below makes the
-- old `AW-YYYY-NNNNNN` format physically unrepresentable — any attempt
-- to insert one fails at the DB layer.
--
-- See audits/cert-code-redesign-plan.md for the full design.

-- Step 1: tighten the cert_code column with a CHECK constraint enforcing
-- the new format. This rejects any legacy `AW-YYYY-NNNNNN` insertion at
-- the DB level so the old format physically cannot re-enter the codebase.
--
-- Pattern: `AW-` then five Crockford Base32 chars, hyphen, five more,
-- hyphen, one check char. All uppercase. The four omitted Crockford
-- letters (I/L/O/U) are excluded from BOTH the random body class AND
-- the check digit class (per the rejection-sampling decision in
-- lib/learner/cert-code.ts).
ALTER TABLE certificates
  ADD CONSTRAINT certificates_cert_code_format_chk
  CHECK (cert_code ~ '^AW-[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]$');

-- Step 2: existing UNIQUE constraint is preserved (already on the
-- column from initial schema). No change.

-- Step 3: NO data backfill in SQL. Pre-launch, the only rows in
-- `certificates` are dev seed data — they fail the new CHECK and are
-- regenerated by re-running `pnpm db:reset`, which truncates first and
-- then re-seeds against the new constraint cleanly.
